help:
	make -C /home/jka/src/android/Juggluco/html  help 	
	cp -a /f/jka/android/Juggluco/Glucodata/Common/src/main/res/values-?? .
	cp -a /f/jka/android/Juggluco/Glucodata/Common/src/main/res/values/strings.xml .
	cp /f/jka/android/Juggluco/Glucodata/Common/src/main/cpp/curve/*jugglucotext.cpp .

